// Enum for filter operator types
export enum FilterOperatorType {
  EQUALS = 'EQUALS',
  CONTAINS = 'CONTAINS',
  REGEXP_PARTIAL_MATCH = 'REGEXP_PARTIAL_MATCH',
  REGEXP_EXACT_MATCH = 'REGEXP_EXACT_MATCH',
  IN_LIST = 'IN_LIST',
  IS_NULL = 'IS_NULL',
  BETWEEN = 'BETWEEN',
  NUMERIC_GREATER_THAN = 'NUMERIC_GREATER_THAN',
  NUMERIC_GREATER_THAN_OR_EQUAL = 'NUMERIC_GREATER_THAN_OR_EQUAL',
  NUMERIC_LESS_THAN = 'NUMERIC_LESS_THAN',
  NUMERIC_LESS_THAN_OR_EQUAL = 'NUMERIC_LESS_THAN_OR_EQUAL',
}
