export enum ConnectorSpecificationAttribute {
  MANUAL_BACKFILL = 'MANUAL_BACKFILL',
  HIDE_IN_CONFIG_FORM = 'HIDE_IN_CONFIG_FORM',
  DEPRECATED = 'DEPRECATED',
  PINNED = 'PINNED',
  DYNAMIC_OPTIONS = 'DYNAMIC_OPTIONS',
}
