export enum DataQualitySummaryState {
  NEVER_RUN = 'NEVER_RUN',
  QUEUED = 'QUEUED',
  RUNNING = 'RUNNING',
  PASSED = 'PASSED',
  ISSUES = 'ISSUES',
  EXECUTION_FAILED = 'EXECUTION_FAILED',
  RESTRICTED = 'RESTRICTED',
  CANCELLED = 'CANCELLED',
  ALL_DISABLED = 'ALL_DISABLED',
}
