/**
 * Copyright (c) OWOX, Inc.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

var adStatisticsFields = {
  'Clicks': {
    'description': 'The number of clicks driven by your ads.',
    'type': 'Integer',
    'fieldType': 'metric'
  },
  'Displays': {
    'description': 'The number of ad impressions served on publishers via Criteo.',
    'type': 'Integer',
    'fieldType': 'metric'
  },
  'ViewableDisplays': {
    'description': 'The number of ads that have been viewed. A display is considered viewed if at least 50% of the ad appears on the screen for at least one second.',
    'type': 'Integer',
    'fieldType': 'metric'
  },
  'NonViewableDisplays': {
    'description': 'The number of ads that have not been viewed',
    'type': 'Integer',
    'fieldType': 'metric'
  },
  'UntrackableDisplays': {
    'description': 'The number of untracked displays. Some displays cannot be tracked because of the display environment (for instance, native banner).',
    'type': 'Integer',
    'fieldType': 'metric'
  },
  'AdvertiserCost': {
    'description': 'Total money spent on Criteo advertising.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'QualifiedVisits': {
    'description': 'The number of users on the target website or app for which at least two events or one sale event occurred within the hour following a click.',
    'type': 'Integer',
    'fieldType': 'metric'
  },
  'Visits': {
    'description': 'The number of users on the target website or app for which at least one event occurred within the hour following a click.',
    'type': 'Integer',
    'fieldType': 'metric'
  },
  'CostPerVisit': {
    'description': 'The amount of money spent per visit to your website or app.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'BounceRate': {
    'description': 'The proportion of website visitors leaving after only viewing one page.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'PotentialDisplays': {
    'description': 'The number of display opportunities, or the number of bid requests received.',
    'type': 'Integer',
    'fieldType': 'metric'
  },
  'OverallCompetitionWin': {
    'description': 'The number of displays divided by the total number of display opportunities.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'ExposedUsers': {
    'description': 'The number of users who have been served an ad.',
    'type': 'Integer',
    'fieldType': 'metric'
  },
  'Audience': {
    'description': 'Potential users who could be served an ad.',
    'type': 'Integer',
    'fieldType': 'metric'
  },
  'Reach': {
    'description': 'Share of potential users who have been served an ad.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'ClickThroughRate': {
    'description': 'Percentage of users served an ad who clicked.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'Cpc': {
    'description': 'Cost per click.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'ECpm': {
    'description': 'Cost per 1000 impressions.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'PostInstallSales': {
    'description': 'The number of your completed events after an app install.',
    'type': 'Integer',
    'fieldType': 'metric'
  },
  'AppInstalls': {
    'description': 'The number of installations of your app.',
    'type': 'Integer',
    'fieldType': 'metric'
  },
  'PostInstallConversionRate': {
    'description': 'Percentage of post-install sales compared to the clicks that occurred.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'PostInstallCostOfSale': {
    'description': 'The cost of sale for app install campaigns.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'PostInstallOrderValue': {
    'description': 'The amount of money generated by sales after an app install.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'CostPerInstall': {
    'description': 'The ad cost per app install.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'InstallRate': {
    'description': 'The percentage of completed app installs compared to the number of clicks.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'PostInstallCostPerOrder': {
    'description': 'The cost per order for sales after an app install.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'PostInstallRoas': {
    'description': 'The return on ad spend for sales after an app install.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'SalesClientAttribution': {
    'description': 'The number of transactions or conversions resulting from Criteo ads.',
    'type': 'Integer',
    'fieldType': 'metric'
  },
  'SalesAllClientAttribution': {
    'description': 'The number of transactions or conversions resulting from Criteo ads.',
    'type': 'Integer',
    'fieldType': 'metric'
  },
  'SalesPc30d': {
    'description': 'The number of transactions or conversions resulting from Criteo ads.',
    'type': 'Integer',
    'fieldType': 'metric'
  },
  'SalesAllPc30d': {
    'description': 'The number of transactions or conversions resulting from Criteo ads.',
    'type': 'Integer',
    'fieldType': 'metric'
  },
  'SalesPv24h': {
    'description': 'The number of transactions or conversions resulting from Criteo ads.',
    'type': 'Integer',
    'fieldType': 'metric'
  },
  'SalesAllPv24h': {
    'description': 'The number of transactions or conversions resulting from Criteo ads.',
    'type': 'Integer',
    'fieldType': 'metric'
  },
  'SalesPc30dPv24h': {
    'description': 'The number of transactions or conversions resulting from Criteo ads.',
    'type': 'Integer',
    'fieldType': 'metric'
  },
  'SalesAllPc30dPv24h': {
    'description': 'The number of transactions or conversions resulting from Criteo ads.',
    'type': 'Integer',
    'fieldType': 'metric'
  },
  'SalesPc1d': {
    'description': 'The number of transactions or conversions resulting from Criteo ads.',
    'type': 'Integer',
    'fieldType': 'metric'
  },
  'SalesAllPc1d': {
    'description': 'The number of transactions or conversions resulting from Criteo ads.',
    'type': 'Integer',
    'fieldType': 'metric'
  },
  'SalesPc7d': {
    'description': 'The number of transactions or conversions resulting from Criteo ads.',
    'type': 'Integer',
    'fieldType': 'metric'
  },
  'SalesAllPc7d': {
    'description': 'The number of transactions or conversions resulting from Criteo ads.',
    'type': 'Integer',
    'fieldType': 'metric'
  },
  'RevenueGeneratedClientAttribution': {
    'description': 'The amount of money generated by online sales.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'RevenueGeneratedAllClientAttribution': {
    'description': 'The amount of money generated by online sales.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'RevenueGeneratedPc30d': {
    'description': 'The amount of money generated by online sales.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'RevenueGeneratedAllPc30d': {
    'description': 'The amount of money generated by online sales.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'RevenueGeneratedPv24h': {
    'description': 'The amount of money generated by online sales.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'RevenueGeneratedAllPv24h': {
    'description': 'The amount of money generated by online sales.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'RevenueGeneratedPc30dPv24h': {
    'description': 'The amount of money generated by online sales.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'RevenueGeneratedAllPc30dPv24h': {
    'description': 'The amount of money generated by online sales.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'RevenueGeneratedPc1d': {
    'description': 'The amount of money generated by online sales.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'RevenueGeneratedAllPc1d': {
    'description': 'The amount of money generated by online sales.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'RevenueGeneratedPc7d': {
    'description': 'The amount of money generated by online sales.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'RevenueGeneratedAllPc7d': {
    'description': 'The amount of money generated by online sales.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'AverageCartClientAttribution': {
    'description': 'Average revenue generated by a conversion or sale.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'AverageCartAllClientAttribution': {
    'description': 'Average revenue generated by a conversion or sale.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'AverageCartPc30d': {
    'description': 'Average revenue generated by a conversion or sale.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'AverageCartAllPc30d': {
    'description': 'Average revenue generated by a conversion or sale.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'AverageCartPv24h': {
    'description': 'Average revenue generated by a conversion or sale.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'AverageCartAllPv24h': {
    'description': 'Average revenue generated by a conversion or sale.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'AverageCartPc30dPv24h': {
    'description': 'Average revenue generated by a conversion or sale.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'AverageCartAllPc30dPv24h': {
    'description': 'Average revenue generated by a conversion or sale.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'AverageCartPc1d': {
    'description': 'Average revenue generated by a conversion or sale.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'AverageCartAllPc1d': {
    'description': 'Average revenue generated by a conversion or sale.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'AverageCartPc7d': {
    'description': 'Average revenue generated by a conversion or sale.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'AverageCartAllPc7d': {
    'description': 'Average revenue generated by a conversion or sale.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'ConversionRateClientAttribution': {
    'description': 'Percentage of conversions or sales compared to the clicks that occurred.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'ConversionRateAllClientAttribution': {
    'description': 'Percentage of conversions or sales compared to the clicks that occurred.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'ConversionRatePc30d': {
    'description': 'Percentage of conversions or sales compared to the clicks that occurred.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'ConversionRateAllPc30d': {
    'description': 'Percentage of conversions or sales compared to the clicks that occurred.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'ConversionRatePv24h': {
    'description': 'Percentage of conversions or sales compared to the clicks that occurred.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'ConversionRateAllPv24h': {
    'description': 'Percentage of conversions or sales compared to the clicks that occurred.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'ConversionRatePc30dPv24h': {
    'description': 'Percentage of conversions or sales compared to the clicks that occurred.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'ConversionRateAllPc30dPv24h': {
    'description': 'Percentage of conversions or sales compared to the clicks that occurred.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'ConversionRatePc1d': {
    'description': 'Percentage of conversions or sales compared to the clicks that occurred.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'ConversionRateAllPc1d': {
    'description': 'Percentage of conversions or sales compared to the clicks that occurred.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'ConversionRatePc7d': {
    'description': 'Percentage of conversions or sales compared to the clicks that occurred.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'ConversionRateAllPc7d': {
    'description': 'Percentage of conversions or sales compared to the clicks that occurred.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'ECosClientAttribution': {
    'description': 'Advertising cost per conversion or sale.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'ECosAllClientAttribution': {
    'description': 'Advertising cost per conversion or sale.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'ECosPc30d': {
    'description': 'Advertising cost per conversion or sale.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'ECosAllPc30d': {
    'description': 'Advertising cost per conversion or sale.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'ECosPv24h': {
    'description': 'Advertising cost per conversion or sale.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'ECosAllPv24h': {
    'description': 'Advertising cost per conversion or sale.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'ECosPc30dPv24h': {
    'description': 'Advertising cost per conversion or sale.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'ECosAllPc30dPv24h': {
    'description': 'Advertising cost per conversion or sale.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'ECosPc1d': {
    'description': 'Advertising cost per conversion or sale.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'ECosAllPc1d': {
    'description': 'Advertising cost per conversion or sale.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'ECosPc7d': {
    'description': 'Advertising cost per conversion or sale.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'ECosAllPc7d': {
    'description': 'Advertising cost per conversion or sale.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'CostPerOrderClientAttribution': {
    'description': 'The price you pay for each order. Calculated as total cost divided by the total number of orders.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'CostPerOrderAllClientAttribution': {
    'description': 'The price you pay for each order. Calculated as total cost divided by the total number of orders.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'CostPerOrderPc30d': {
    'description': 'The price you pay for each order. Calculated as total cost divided by the total number of orders.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'CostPerOrderAllPc30d': {
    'description': 'The price you pay for each order. Calculated as total cost divided by the total number of orders.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'CostPerOrderPv24h': {
    'description': 'The price you pay for each order. Calculated as total cost divided by the total number of orders.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'CostPerOrderAllPv24h': {
    'description': 'The price you pay for each order. Calculated as total cost divided by the total number of orders.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'CostPerOrderPc30dPv24h': {
    'description': 'The price you pay for each order. Calculated as total cost divided by the total number of orders.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'CostPerOrderAllPc30dPv24h': {
    'description': 'The price you pay for each order. Calculated as total cost divided by the total number of orders.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'CostPerOrderPc1d': {
    'description': 'The price you pay for each order. Calculated as total cost divided by the total number of orders.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'CostPerOrderAllPc1d': {
    'description': 'The price you pay for each order. Calculated as total cost divided by the total number of orders.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'CostPerOrderPc7d': {
    'description': 'The price you pay for each order. Calculated as total cost divided by the total number of orders.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'CostPerOrderAllPc7d': {
    'description': 'The price you pay for each order. Calculated as total cost divided by the total number of orders.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'RoasClientAttribution': {
    'description': 'The ratio between revenue generated and the cost.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'RoasAllClientAttribution': {
    'description': 'The ratio between revenue generated and the cost.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'RoasPc30d': {
    'description': 'The ratio between revenue generated and the cost.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'RoasAllPc30d': {
    'description': 'The ratio between revenue generated and the cost.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'RoasPv24h': {
    'description': 'The ratio between revenue generated and the cost.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'RoasAllPv24h': {
    'description': 'The ratio between revenue generated and the cost.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'RoasPc30dPv24h': {
    'description': 'The ratio between revenue generated and the cost.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'RoasAllPc30dPv24h': {
    'description': 'The ratio between revenue generated and the cost.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'RoasPc1d': {
    'description': 'The ratio between revenue generated and the cost.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'RoasAllPc1d': {
    'description': 'The ratio between revenue generated and the cost.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'RoasPc7d': {
    'description': 'The ratio between revenue generated and the cost.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'RoasAllPc7d': {
    'description': 'The ratio between revenue generated and the cost.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'AdvertiserValue': {
    'description': 'The revenue generated by each product, considering margin (if provided in your product catalog).',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'AdvertiserAllValue': {
    'description': 'The revenue generated by each product, considering margin (if provided in your product catalog).',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'CostOfAdvertiserValue': {
    'description': 'The ratio between the advertiser value generated by sales and the cost of the campaign(s), given as a percentage.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'CostOfAdvertiserValueAll': {
    'description': 'The ratio between the advertiser value generated by sales and the cost of the campaign(s), given as a percentage.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'OmnichannelRoasClientAttribution': {
    'description': 'The ratio between revenue generated online and offline, and the cost.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'OmnichannelRoasPc30d': {
    'description': 'The ratio between revenue generated online and offline, and the cost.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'OmnichannelRoasAllPc30d': {
    'description': 'The ratio between revenue generated online and offline, and the cost.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'OmnichannelRoasPv24h': {
    'description': 'The ratio between revenue generated online and offline, and the cost.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'OmnichannelRoasAllPv24h': {
    'description': 'The ratio between revenue generated online and offline, and the cost.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'OmnichannelRevenueClientAttribution': {
    'description': 'The revenue generated by online and offline sales.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'OmnichannelRevenuePc30d': {
    'description': 'The revenue generated by online and offline sales.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'OmnichannelRevenueAllPc30d': {
    'description': 'The revenue generated by online and offline sales.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'OmnichannelRevenuePv24h': {
    'description': 'The revenue generated by online and offline sales.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'OmnichannelRevenueAllPv24h': {
    'description': 'The revenue generated by online and offline sales.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'OmnichannelsalesClientAttribution': {
    'description': 'The number of online and offline transactions or conversions resulting from Criteo ads.',
    'type': 'Integer',
    'fieldType': 'metric'
  },
  'OmnichannelSalesPc30d': {
    'description': 'The number of online and offline transactions or conversions resulting from Criteo ads.',
    'type': 'Integer',
    'fieldType': 'metric'
  },
  'OmnichannelSalesAllPc30d': {
    'description': 'The number of online and offline transactions or conversions resulting from Criteo ads.',
    'type': 'Integer',
    'fieldType': 'metric'
  },
  'OmnichannelSalesPv24h': {
    'description': 'The number of online and offline transactions or conversions resulting from Criteo ads.',
    'type': 'Integer',
    'fieldType': 'metric'
  },
  'OmnichannelSalesAllPv24h': {
    'description': 'The number of online and offline transactions or conversions resulting from Criteo ads.',
    'type': 'Integer',
    'fieldType': 'metric'
  },
  'RoasOfflinePc30d': {
    'description': 'The ratio between the revenue generated offline and the cost.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'RoasOfflinePv24h': {
    'description': 'The ratio between the revenue generated offline and the cost.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'SalesOfflinePc30d': {
    'description': 'The number of completed in-store transactions or purchases.',
    'type': 'Integer',
    'fieldType': 'metric'
  },
  'SalesOfflinePv24h': {
    'description': 'The number of completed in-store transactions or purchases.',
    'type': 'Integer',
    'fieldType': 'metric'
  },
  'RevenueGeneratedOfflinePc30d': {
    'description': 'The amount of revenue generated by in-store sales.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'RevenueGeneratedOfflinePv24h': {
    'description': 'The amount of revenue generated by in-store sales.',
    'type': 'Decimal',
    'fieldType': 'metric'
  },
  'Day': {
    'description': 'The day of the statistics data (YYYY-MM-DD format).',
    'type': 'Date',
    'fieldType': 'dimension',
    'GoogleBigQueryType': 'date',
    'GoogleBigQueryPartitioned': true,
    'GoogleSheetsFormat': '@'
  },
  'Campaign': {
    'description': 'The campaign name.',
    'type': 'String',
    'fieldType': 'dimension'
  },
  'CampaignId': {
    'description': 'The unique identifier for the campaign.',
    'type': 'String',
    'fieldType': 'dimension'
  },
  'AdvertiserId': {
    'description': 'The unique identifier for the advertiser.',
    'type': 'String',
    'fieldType': 'dimension'
  },
  'Advertiser': {
    'description': 'The advertiser name.',
    'type': 'String',
    'fieldType': 'dimension'
  },
  'Adset': {
    'description': 'The adset name.',
    'type': 'String',
    'fieldType': 'dimension'
  },
  'AdsetId': {
    'description': 'The unique identifier for the adset.',
    'type': 'String',
    'fieldType': 'dimension'
  },
  'Ad': {
    'description': 'The ad name.',
    'type': 'String',
    'fieldType': 'dimension'
  },
  'AdId': {
    'description': 'The unique identifier for the ad.',
    'type': 'String',
    'fieldType': 'dimension'
  },
  'Currency': {
    'description': 'The currency of the advertiser cost.',
    'type': 'String'
  }
};
