export enum SystemTriggerType {
  RETRY_INTERRUPTED_CONNECTOR_RUNS = 'RETRY_INTERRUPTED_CONNECTOR_RUNS',
  RUNS_NOTIFICATION = 'RUNS_NOTIFICATION',
  SEND_NOTIFICATIONS = 'SEND_NOTIFICATIONS',
  SEARCH_INDEX_DRIFT = 'SEARCH_INDEX_DRIFT',
  PLUGIN_UPDATE_CHECK = 'PLUGIN_UPDATE_CHECK',
}
