export enum DataStorageType {
  GOOGLE_BIGQUERY = 'GOOGLE_BIGQUERY',
  AWS_ATHENA = 'AWS_ATHENA',
  SNOWFLAKE = 'SNOWFLAKE',
  DATABRICKS = 'DATABRICKS',
  AWS_REDSHIFT = 'AWS_REDSHIFT',
  AZURE_SYNAPSE = 'AZURE_SYNAPSE',
}
