export enum DataMartColumnKey {
  TITLE = 'title',
  DEFINITION_TYPE = 'definitionType',
  STORAGE_TYPE = 'storageType',
  STATUS = 'status',
  TRIGGERS_COUNT = 'triggersCount',
  REPORTS_COUNT = 'reportsCount',
  CREATED_AT = 'createdAt',
  CREATED_BY_USER = 'createdByUser',
  HEALTH_STATUS = 'healthStatus',
  BUSINESS_OWNERS = 'businessOwnerUsers',
  TECHNICAL_OWNERS = 'technicalOwnerUsers',
  CONTEXTS = 'contexts',
  AVAILABLE_FOR_REPORTING = 'availableForReporting',
  AVAILABLE_FOR_MAINTENANCE = 'availableForMaintenance',
  DATA_LAST_UPDATED = 'dataLastUpdated',
}
