import {
  Activity,
  BadgeCheck,
  BadgeDollarSign,
  BellRing,
  Blocks,
  Box,
  Braces,
  Building2,
  Calendar,
  ChartColumn,
  ChartNoAxesCombined,
  ChartPie,
  Cloud,
  Coins,
  CreditCard,
  Database,
  DatabaseZap,
  Eye,
  FileCode,
  FileSpreadsheet,
  FileText,
  Filter,
  Fingerprint,
  Flag,
  FlaskConical,
  Gauge,
  Globe,
  Goal,
  Handshake,
  Image,
  Layers,
  LayoutDashboard,
  LayoutTemplate,
  LifeBuoy,
  Mail,
  MapPin,
  Megaphone,
  Merge,
  MessageCircle,
  MousePointerClick,
  Newspaper,
  Package,
  Phone,
  PiggyBank,
  Radio,
  Receipt,
  Repeat,
  Route,
  ScanEye,
  ScrollText,
  Search,
  Server,
  Sheet,
  ShoppingBag,
  ShoppingCart,
  Sigma,
  Smartphone,
  Star,
  Store,
  Table,
  Tag,
  Target,
  TicketPercent,
  TrendingUp,
  Truck,
  Undo2,
  User,
  UserPlus,
  Users,
  Video,
  Wallet,
  Warehouse,
  Webhook,
  Workflow,
  type LucideIcon,
} from 'lucide-react';
import type { DataMartIconKey } from '../../enums/data-mart-icon.enum';

export type { DataMartIconKey } from '../../enums/data-mart-icon.enum';

/**
 * Glyph and label for every icon key a user can pick (`DATA_MART_ICON_KEYS`),
 * in picker order.
 */
export const DATA_MART_ICON_OPTIONS = [
  { key: 'purchases', label: 'Purchases', icon: ShoppingCart },
  { key: 'orders', label: 'Orders', icon: Receipt },
  { key: 'products', label: 'Products', icon: Package },
  { key: 'inventory', label: 'Inventory', icon: Warehouse },
  { key: 'revenue', label: 'Revenue', icon: TrendingUp },
  { key: 'finance', label: 'Finance', icon: Wallet },
  { key: 'ad-spend', label: 'Ad spend', icon: BadgeDollarSign },
  { key: 'campaigns', label: 'Campaigns', icon: Target },
  { key: 'traffic-sources', label: 'Traffic sources', icon: Megaphone },
  { key: 'sessions', label: 'Sessions', icon: MousePointerClick },
  { key: 'pageviews', label: 'Pageviews', icon: Eye },
  { key: 'events', label: 'Events', icon: Activity },
  { key: 'conversions', label: 'Conversions', icon: Flag },
  { key: 'customers', label: 'Customers', icon: Users },
  { key: 'users', label: 'Users', icon: User },
  { key: 'leads', label: 'Leads', icon: UserPlus },
  { key: 'countries', label: 'Countries', icon: MapPin },
  { key: 'devices', label: 'Devices', icon: Smartphone },
  { key: 'email', label: 'Email', icon: Mail },
  { key: 'keywords', label: 'Keywords', icon: Search },
  { key: 'social', label: 'Social', icon: MessageCircle },
  { key: 'subscriptions', label: 'Subscriptions', icon: Repeat },
  { key: 'calendar', label: 'Calendar', icon: Calendar },
  { key: 'support', label: 'Support', icon: LifeBuoy },
  { key: 'database', label: 'Database', icon: Database },
  { key: 'table', label: 'Table', icon: Table },
  { key: 'payments', label: 'Payments', icon: CreditCard },
  { key: 'invoices', label: 'Invoices', icon: FileText },
  { key: 'refunds', label: 'Refunds', icon: Undo2 },
  { key: 'carts', label: 'Carts', icon: ShoppingBag },
  { key: 'shipping', label: 'Shipping', icon: Truck },
  { key: 'promotions', label: 'Promotions', icon: TicketPercent },
  { key: 'stores', label: 'Stores', icon: Store },
  { key: 'exchange-rates', label: 'Exchange rates', icon: Coins },
  { key: 'creatives', label: 'Creatives', icon: Image },
  { key: 'video', label: 'Video', icon: Video },
  { key: 'websites', label: 'Websites', icon: Globe },
  { key: 'landing-pages', label: 'Landing pages', icon: LayoutTemplate },
  { key: 'content', label: 'Content', icon: Newspaper },
  { key: 'deals', label: 'Deals', icon: Handshake },
  { key: 'companies', label: 'Companies', icon: Building2 },
  { key: 'calls', label: 'Calls', icon: Phone },
  { key: 'reviews', label: 'Reviews', icon: Star },
  { key: 'funnels', label: 'Funnels', icon: Filter },
  { key: 'segments', label: 'Segments', icon: ChartPie },
  { key: 'experiments', label: 'Experiments', icon: FlaskConical },
  { key: 'kpis', label: 'KPIs', icon: Gauge },
  { key: 'forecasts', label: 'Forecasts', icon: ChartNoAxesCombined },
  { key: 'data-sources', label: 'Data sources', icon: DatabaseZap },
  { key: 'pipelines', label: 'Pipelines', icon: Workflow },
  { key: 'sql', label: 'SQL', icon: FileCode },
  { key: 'api', label: 'API', icon: Webhook },
  { key: 'cloud', label: 'Cloud', icon: Cloud },
  { key: 'servers', label: 'Servers', icon: Server },
  { key: 'reports', label: 'Reports', icon: FileSpreadsheet },
  { key: 'spreadsheets', label: 'Spreadsheets', icon: Sheet },
  { key: 'dashboards', label: 'Dashboards', icon: LayoutDashboard },
  { key: 'charts', label: 'Charts', icon: ChartColumn },
  { key: 'joins', label: 'Joins', icon: Merge },
  { key: 'schemas', label: 'Schemas', icon: Braces },
  { key: 'dimensions', label: 'Dimensions', icon: Layers },
  { key: 'metrics', label: 'Metrics', icon: Sigma },
  { key: 'data-quality', label: 'Data quality', icon: BadgeCheck },
  { key: 'history', label: 'History', icon: ScrollText },
  { key: 'utm', label: 'UTM tags', icon: Tag },
  { key: 'attribution', label: 'Attribution', icon: Route },
  { key: 'channels', label: 'Channels', icon: Radio },
  { key: 'budgets', label: 'Budgets', icon: PiggyBank },
  { key: 'goals', label: 'Goals', icon: Goal },
  { key: 'identities', label: 'Identities', icon: Fingerprint },
  { key: 'cohorts', label: 'Cohorts', icon: Blocks },
  { key: 'alerts', label: 'Alerts', icon: BellRing },
  { key: 'impressions', label: 'Impressions', icon: ScanEye },
] as const satisfies readonly {
  key: DataMartIconKey;
  label: string;
  icon: LucideIcon;
}[];

/** Shown when a Data Mart has no icon picked. */
export const DEFAULT_DATA_MART_ICON: LucideIcon = Box;

const ICONS_BY_KEY = new Map<string, LucideIcon>(
  DATA_MART_ICON_OPTIONS.map(option => [option.key, option.icon])
);

/** The icon to draw for a Data Mart; unknown or missing keys fall back to the default. */
export function getDataMartIcon(key: string | null | undefined): LucideIcon {
  return (key ? ICONS_BY_KEY.get(key) : undefined) ?? DEFAULT_DATA_MART_ICON;
}
