/**
 * Copyright (c) OWOX, Inc.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

var ShopifyFieldsSchema = {
  "abandoned-checkouts": {
    "overview": "Abandoned Checkouts",
    "description": "Checkout sessions that did not complete — customer info, items, and pricing for recovery campaigns.",
    "documentation": "https://shopify.dev/docs/api/admin-graphql/2026-07/queries/abandonedcheckouts",
    "fields": abandonedCheckoutsFields,
    "uniqueKeys": ["id"],
    "defaultFields": ["id", "createdAt", "updatedAt", "completedAt", "totalPriceSet", "lineItemsQuantity", "customerId", "customerEmail", "shippingAddressCity", "shippingAddressCountry"],
    "destinationName": "shopify_abandoned_checkouts",
    "queryName": "abandonedCheckouts",
    "connectionPath": "abandonedCheckouts",
    "isTimeSeries": true,
    "queryFilterTemplate": "query: \"updated_at:>='{{startDate}}' AND updated_at:<='{{endDate}}'\""
  },
  "articles": {
    "overview": "Articles",
    "description": "Blog articles — title, author, publication status, and timestamps.",
    "documentation": "https://shopify.dev/docs/api/admin-graphql/2026-07/objects/Article",
    "fields": articlesFields,
    "uniqueKeys": ["id"],
    "defaultFields": ["id", "title", "handle", "blogId", "blogTitle", "isPublished", "publishedAt", "authorName", "createdAt", "updatedAt"],
    "destinationName": "shopify_articles",
    "queryName": "articles",
    "connectionPath": "articles",
    "isTimeSeries": false
  },
  "blogs": {
    "overview": "Blogs",
    "description": "Blogs in the store — title, handle, and template settings.",
    "documentation": "https://shopify.dev/docs/api/admin-graphql/2026-07/objects/Blog",
    "fields": blogsFields,
    "uniqueKeys": ["id"],
    "defaultFields": ["id", "title", "handle", "templateSuffix", "createdAt", "updatedAt"],
    "destinationName": "shopify_blogs",
    "queryName": "blogs",
    "connectionPath": "blogs",
    "isTimeSeries": false
  },
  "collections": {
    "overview": "Collections",
    "description": "Product collections — title, sort order, product count, and last updated.",
    "documentation": "https://shopify.dev/docs/api/admin-graphql/2026-07/objects/Collection",
    "fields": collectionsFields,
    "uniqueKeys": ["id"],
    "defaultFields": ["id", "title", "handle", "description", "sortOrder", "productsCount", "updatedAt"],
    "destinationName": "shopify_collections",
    "queryName": "collections",
    "connectionPath": "collections",
    "isTimeSeries": false
  },
  "customers": {
    "overview": "Customers",
    "description": "Customer accounts — contact info, marketing consent, order history, and lifetime spend.",
    "documentation": "https://shopify.dev/docs/api/admin-graphql/2026-07/objects/Customer",
    "fields": customersFields,
    "uniqueKeys": ["id"],
    "defaultFields": ["id", "displayName", "email", "phone", "state", "numberOfOrders", "amountSpent", "emailMarketingConsentState", "defaultAddressCity", "defaultAddressCountry", "createdAt", "updatedAt"],
    "destinationName": "shopify_customers",
    "queryName": "customers",
    "connectionPath": "customers",
    "isTimeSeries": true,
    "queryFilterTemplate": "query: \"updated_at:>='{{startDate}}' AND updated_at:<='{{endDate}}'\""
  },
  "discount-codes": {
    "overview": "Discount Codes",
    "description": "Discount codes — type, status, usage limits, and validity window.",
    "documentation": "https://shopify.dev/docs/api/admin-graphql/2026-07/objects/DiscountCodeNode",
    "fields": discountCodesFields,
    "uniqueKeys": ["id"],
    "defaultFields": ["id", "code", "discountType", "title", "status", "startsAt", "endsAt", "usageLimit", "asyncUsageCount"],
    "destinationName": "shopify_discount_codes",
    "queryName": "codeDiscountNodes",
    "connectionPath": "codeDiscountNodes",
    "isTimeSeries": false,
    "unionField": "codeDiscount",
    "unionTypes": ["DiscountCodeBasic", "DiscountCodeBxgy", "DiscountCodeFreeShipping"]
  },
  "fulfillment-orders": {
    "overview": "Fulfillment Orders",
    "description": "Fulfillment orders — items to ship, assigned location, delivery method, and status.",
    "documentation": "https://shopify.dev/docs/api/admin-graphql/2026-07/objects/FulfillmentOrder",
    "fields": fulfillmentOrdersFields,
    "uniqueKeys": ["id"],
    "defaultFields": ["id", "status", "requestStatus", "orderId", "orderName", "assignedLocationId", "assignedLocationName", "deliveryMethod", "createdAt", "updatedAt"],
    "destinationName": "shopify_fulfillment_orders",
    "queryName": "fulfillmentOrders",
    "connectionPath": "fulfillmentOrders",
    "isTimeSeries": false
  },
  "inventory-items": {
    "overview": "Inventory Items",
    "description": "Inventory items (SKUs) — tracking status, shipping requirements, and country of origin.",
    "documentation": "https://shopify.dev/docs/api/admin-graphql/2026-07/objects/InventoryItem",
    "fields": inventoryItemsFields,
    "uniqueKeys": ["id"],
    "defaultFields": ["id", "sku", "tracked", "requiresShipping", "variantId", "countryCodeOfOrigin", "createdAt", "updatedAt"],
    "destinationName": "shopify_inventory_items",
    "queryName": "inventoryItems",
    "connectionPath": "inventoryItems",
    "isTimeSeries": false
  },
  "locations": {
    "overview": "Locations",
    "description": "Physical and virtual store locations — activity status, fulfillment capabilities, and address.",
    "documentation": "https://shopify.dev/docs/api/admin-graphql/2026-07/objects/Location",
    "fields": locationsFields,
    "uniqueKeys": ["id"],
    "defaultFields": ["id", "name", "isActive", "isPrimary", "fulfillsOnlineOrders", "city", "country", "createdAt", "updatedAt"],
    "destinationName": "shopify_locations",
    "queryName": "locations",
    "connectionPath": "locations",
    "isTimeSeries": false
  },
  "orders": {
    "overview": "Orders",
    "description": "Orders placed in the store — financial and fulfillment status, customer info, totals, and timestamps.",
    "documentation": "https://shopify.dev/docs/api/admin-graphql/2026-07/objects/Order",
    "fields": ordersFields,
    "uniqueKeys": ["id"],
    "defaultFields": ["id", "name", "displayFinancialStatus", "displayFulfillmentStatus", "customerId", "customerEmail", "currencyCode", "totalPrice", "totalTax", "totalShippingPrice", "totalDiscounts", "totalRefunded", "processedAt", "createdAt", "updatedAt"],
    "destinationName": "shopify_orders",
    "queryName": "orders",
    "connectionPath": "orders",
    "isTimeSeries": true,
    "queryFilterTemplate": "query: \"updated_at:>='{{startDate}}' AND updated_at:<='{{endDate}}'\""
  },
  "products": {
    "overview": "Products",
    "description": "Products in the store catalog — vendor, type, status, inventory, and price range.",
    "documentation": "https://shopify.dev/docs/api/admin-graphql/2026-07/objects/Product",
    "fields": productsFields,
    "uniqueKeys": ["id"],
    "defaultFields": ["id", "title", "handle", "vendor", "productType", "status", "totalInventory", "variantsCount", "priceRangeMinAmount", "priceRangeMaxAmount", "publishedAt", "createdAt", "updatedAt"],
    "destinationName": "shopify_products",
    "queryName": "products",
    "connectionPath": "products",
    "isTimeSeries": true,
    "queryFilterTemplate": "query: \"updated_at:>='{{startDate}}' AND updated_at:<='{{endDate}}'\""
  },
  "product-variants": {
    "overview": "Product Variants",
    "description": "Product variants — SKU, price, inventory quantity, and availability.",
    "documentation": "https://shopify.dev/docs/api/admin-graphql/2026-07/objects/ProductVariant",
    "fields": productVariantsFields,
    "uniqueKeys": ["id"],
    "defaultFields": ["id", "displayName", "sku", "productId", "productTitle", "price", "compareAtPrice", "inventoryQuantity", "availableForSale", "createdAt", "updatedAt"],
    "destinationName": "shopify_product_variants",
    "queryName": "productVariants",
    "connectionPath": "productVariants",
    "isTimeSeries": false
  },
  "pages": {
    "overview": "Pages",
    "description": "Static store pages — title, handle, publication status, and timestamps.",
    "documentation": "https://shopify.dev/docs/api/admin-graphql/2026-07/objects/Page",
    "fields": pagesFields,
    "uniqueKeys": ["id"],
    "defaultFields": ["id", "title", "handle", "isPublished", "publishedAt", "createdAt", "updatedAt"],
    "destinationName": "shopify_pages",
    "queryName": "pages",
    "connectionPath": "pages",
    "isTimeSeries": false
  },
  "shop": {
    "overview": "Shop",
    "description": "Store settings — domain, currency, timezone, and plan details.",
    "documentation": "https://shopify.dev/docs/api/admin-graphql/2026-07/objects/Shop",
    "fields": shopFields,
    "uniqueKeys": ["id"],
    "defaultFields": ["id", "name", "email", "myshopifyDomain", "primaryDomain", "currencyCode", "ianaTimezone", "plan", "createdAt"],
    "destinationName": "shopify_shop",
    "queryName": "shop",
    "connectionPath": "shop",
    "isSingleton": true,
    "isTimeSeries": false
  },
  "tender-transactions": {
    "overview": "Tender Transactions",
    "description": "Payment tender transactions — amount, currency, order reference, and processing time.",
    "documentation": "https://shopify.dev/docs/api/admin-graphql/2026-07/objects/TenderTransaction",
    "fields": tenderTransactionsFields,
    "uniqueKeys": ["id"],
    "defaultFields": ["id", "amount", "currencyCode", "orderId", "remoteReference", "test", "processedAt"],
    "destinationName": "shopify_tender_transactions",
    "queryName": "tenderTransactions",
    "connectionPath": "tenderTransactions",
    "isTimeSeries": false
  },
  "metafield-articles": {
    "overview": "Article Metafields",
    "description": "Custom metadata attached to articles — namespace, key, value, and type.",
    "documentation": "https://shopify.dev/docs/api/admin-graphql/2026-07/objects/Metafield",
    "fields": metafieldsFields,
    "uniqueKeys": ["id"],
    "defaultFields": ["id", "namespace", "key", "value", "type", "ownerId", "ownerType", "createdAt", "updatedAt"],
    "destinationName": "shopify_metafield_articles",
    "ownerType": "ARTICLE",
    "parentQuery": "articles",
    "isTimeSeries": false
  },
  "metafield-blogs": {
    "overview": "Blog Metafields",
    "description": "Custom metadata attached to blogs — namespace, key, value, and type.",
    "documentation": "https://shopify.dev/docs/api/admin-graphql/2026-07/objects/Metafield",
    "fields": metafieldsFields,
    "uniqueKeys": ["id"],
    "defaultFields": ["id", "namespace", "key", "value", "type", "ownerId", "ownerType", "createdAt", "updatedAt"],
    "destinationName": "shopify_metafield_blogs",
    "ownerType": "BLOG",
    "parentQuery": "blogs",
    "isTimeSeries": false
  },
  "metafield-collections": {
    "overview": "Collection Metafields",
    "description": "Custom metadata attached to collections — namespace, key, value, and type.",
    "documentation": "https://shopify.dev/docs/api/admin-graphql/2026-07/objects/Metafield",
    "fields": metafieldsFields,
    "uniqueKeys": ["id"],
    "defaultFields": ["id", "namespace", "key", "value", "type", "ownerId", "ownerType", "createdAt", "updatedAt"],
    "destinationName": "shopify_metafield_collections",
    "ownerType": "COLLECTION",
    "parentQuery": "collections",
    "isTimeSeries": false
  },
  "metafield-customers": {
    "overview": "Customer Metafields",
    "description": "Custom metadata attached to customers — namespace, key, value, and type.",
    "documentation": "https://shopify.dev/docs/api/admin-graphql/2026-07/objects/Metafield",
    "fields": metafieldsFields,
    "uniqueKeys": ["id"],
    "defaultFields": ["id", "namespace", "key", "value", "type", "ownerId", "ownerType", "createdAt", "updatedAt"],
    "destinationName": "shopify_metafield_customers",
    "ownerType": "CUSTOMER",
    "parentQuery": "customers",
    "isTimeSeries": false
  },
  "metafield-locations": {
    "overview": "Location Metafields",
    "description": "Custom metadata attached to locations — namespace, key, value, and type.",
    "documentation": "https://shopify.dev/docs/api/admin-graphql/2026-07/objects/Metafield",
    "fields": metafieldsFields,
    "uniqueKeys": ["id"],
    "defaultFields": ["id", "namespace", "key", "value", "type", "ownerId", "ownerType", "createdAt", "updatedAt"],
    "destinationName": "shopify_metafield_locations",
    "ownerType": "LOCATION",
    "parentQuery": "locations",
    "isTimeSeries": false
  },
  "metafield-orders": {
    "overview": "Order Metafields",
    "description": "Custom metadata attached to orders — namespace, key, value, and type.",
    "documentation": "https://shopify.dev/docs/api/admin-graphql/2026-07/objects/Metafield",
    "fields": metafieldsFields,
    "uniqueKeys": ["id"],
    "defaultFields": ["id", "namespace", "key", "value", "type", "ownerId", "ownerType", "createdAt", "updatedAt"],
    "destinationName": "shopify_metafield_orders",
    "ownerType": "ORDER",
    "parentQuery": "orders",
    "isTimeSeries": false
  },
  "metafield-pages": {
    "overview": "Page Metafields",
    "description": "Custom metadata attached to pages — namespace, key, value, and type.",
    "documentation": "https://shopify.dev/docs/api/admin-graphql/2026-07/objects/Metafield",
    "fields": metafieldsFields,
    "uniqueKeys": ["id"],
    "defaultFields": ["id", "namespace", "key", "value", "type", "ownerId", "ownerType", "createdAt", "updatedAt"],
    "destinationName": "shopify_metafield_pages",
    "ownerType": "PAGE",
    "parentQuery": "pages",
    "isTimeSeries": false
  },
  "metafield-product-variants": {
    "overview": "Product Variant Metafields",
    "description": "Custom metadata attached to product variants — namespace, key, value, and type.",
    "documentation": "https://shopify.dev/docs/api/admin-graphql/2026-07/objects/Metafield",
    "fields": metafieldsFields,
    "uniqueKeys": ["id"],
    "defaultFields": ["id", "namespace", "key", "value", "type", "ownerId", "ownerType", "createdAt", "updatedAt"],
    "destinationName": "shopify_metafield_product_variants",
    "ownerType": "PRODUCTVARIANT",
    "parentQuery": "productVariants",
    "isTimeSeries": false
  },
  "metafield-products": {
    "overview": "Product Metafields",
    "description": "Custom metadata attached to products — namespace, key, value, and type.",
    "documentation": "https://shopify.dev/docs/api/admin-graphql/2026-07/objects/Metafield",
    "fields": metafieldsFields,
    "uniqueKeys": ["id"],
    "defaultFields": ["id", "namespace", "key", "value", "type", "ownerId", "ownerType", "createdAt", "updatedAt"],
    "destinationName": "shopify_metafield_products",
    "ownerType": "PRODUCT",
    "parentQuery": "products",
    "isTimeSeries": false
  },
  "metafield-shops": {
    "overview": "Shop Metafields",
    "description": "Custom metadata attached to the shop — namespace, key, value, and type.",
    "documentation": "https://shopify.dev/docs/api/admin-graphql/2026-07/objects/Metafield",
    "fields": metafieldsFields,
    "uniqueKeys": ["id"],
    "defaultFields": ["id", "namespace", "key", "value", "type", "ownerId", "ownerType", "createdAt", "updatedAt"],
    "destinationName": "shopify_metafield_shops",
    "ownerType": "SHOP",
    "parentQuery": null,
    "isTimeSeries": false
  }
};
