/**
 * Copyright (c) OWOX, Inc.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

// API reference: https://shopify.dev/docs/api/admin-graphql/2026-07/objects/Order

var ordersFields = {
  'id': {
    'description': 'A globally-unique ID.',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'id'
  },
  'name': {
    'description': 'The order name, generated by combining the order_number with the shop order prefix.',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'name'
  },
  'email': {
    'description': 'The email address of the customer.',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'email'
  },
  'phone': {
    'description': 'The phone number of the customer.',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'phone'
  },
  'displayFinancialStatus': {
    'description': 'The financial status of the order.',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'displayFinancialStatus'
  },
  'displayFulfillmentStatus': {
    'description': 'The fulfillment status of the order.',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'displayFulfillmentStatus'
  },
  'confirmed': {
    'description': 'Whether the order is confirmed.',
    'type': DATA_TYPES.BOOLEAN,
    'graphqlPath': 'confirmed'
  },
  'closed': {
    'description': 'Whether the order is closed.',
    'type': DATA_TYPES.BOOLEAN,
    'graphqlPath': 'closed'
  },
  'cancelledAt': {
    'description': 'The date and time when the order was cancelled.',
    'type': DATA_TYPES.TIMESTAMP,
    'graphqlPath': 'cancelledAt'
  },
  'cancelReason': {
    'description': 'The reason for cancellation.',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'cancelReason'
  },
  'currencyCode': {
    'description': 'The currency of the order.',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'currencyCode'
  },
  'subtotalPrice': {
    'description': 'The subtotal price of the order.',
    'type': DATA_TYPES.NUMBER,
    'graphqlPath': 'subtotalPriceSet { shopMoney { amount } }'
  },
  'totalPrice': {
    'description': 'The total price of the order.',
    'type': DATA_TYPES.NUMBER,
    'graphqlPath': 'totalPriceSet { shopMoney { amount } }'
  },
  'totalTax': {
    'description': 'The total tax of the order.',
    'type': DATA_TYPES.NUMBER,
    'graphqlPath': 'totalTaxSet { shopMoney { amount } }'
  },
  'totalShippingPrice': {
    'description': 'The total shipping price.',
    'type': DATA_TYPES.NUMBER,
    'graphqlPath': 'totalShippingPriceSet { shopMoney { amount } }'
  },
  'totalDiscounts': {
    'description': 'The total discounts applied.',
    'type': DATA_TYPES.NUMBER,
    'graphqlPath': 'totalDiscountsSet { shopMoney { amount } }'
  },
  'discountCodes': {
    'description': 'Discount codes applied to the order as JSON array (code, amount, type).',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'discountCodes'
  },
  'discountApplications': {
    'description': 'All discount applications (codes, automatic, manual) as JSON array.',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'discountApplications(first: 20) { nodes { allocationMethod targetSelection targetType value { ... on MoneyV2 { amount currencyCode } ... on PricingPercentageValue { percentage } } ... on DiscountCodeApplication { code } ... on AutomaticDiscountApplication { title } ... on ManualDiscountApplication { title description } } }'
  },
  'totalRefunded': {
    'description': 'The total amount refunded.',
    'type': DATA_TYPES.NUMBER,
    'graphqlPath': 'totalRefundedSet { shopMoney { amount } }'
  },
  'totalOutstanding': {
    'description': 'The total amount not yet transacted for the order.',
    'type': DATA_TYPES.NUMBER,
    'graphqlPath': 'totalOutstandingSet { shopMoney { amount } }'
  },
  'totalWeight': {
    'description': 'The total weight of the order.',
    'type': DATA_TYPES.NUMBER,
    'graphqlPath': 'totalWeight'
  },
  'fullyPaid': {
    'description': 'Whether the order is fully paid.',
    'type': DATA_TYPES.BOOLEAN,
    'graphqlPath': 'fullyPaid'
  },
  'taxesIncluded': {
    'description': 'Whether taxes are included in the order subtotal.',
    'type': DATA_TYPES.BOOLEAN,
    'graphqlPath': 'taxesIncluded'
  },
  'taxExempt': {
    'description': 'Whether the order is tax exempt.',
    'type': DATA_TYPES.BOOLEAN,
    'graphqlPath': 'taxExempt'
  },
  'customerId': {
    'description': 'The ID of the customer.',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'customer { id }'
  },
  'customerEmail': {
    'description': 'The email of the customer.',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'customer { email }'
  },
  'shippingAddressCity': {
    'description': 'City from the shipping address.',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'shippingAddress { city }'
  },
  'shippingAddressCountry': {
    'description': 'Country from the shipping address.',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'shippingAddress { country }'
  },
  'shippingAddressProvince': {
    'description': 'Province from the shipping address.',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'shippingAddress { province }'
  },
  'shippingAddressZip': {
    'description': 'Postal/ZIP code from the shipping address.',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'shippingAddress { zip }'
  },
  'billingAddressCity': {
    'description': 'City from the billing address.',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'billingAddress { city }'
  },
  'billingAddressCountry': {
    'description': 'Country from the billing address.',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'billingAddress { country }'
  },
  'billingAddressProvince': {
    'description': 'Province from the billing address.',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'billingAddress { province }'
  },
  'billingAddressZip': {
    'description': 'Postal/ZIP code from the billing address.',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'billingAddress { zip }'
  },
  'tags': {
    'description': 'A comma-separated list of tags.',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'tags'
  },
  'note': {
    'description': 'The note attached to the order.',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'note'
  },
  'sourceName': {
    'description': 'The source of the order.',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'sourceName'
  },
  'checkoutToken': {
    'description': 'Token of the checkout that created the order. Useful for correlating the order with Web Pixel checkout events. NULL when no checkout is associated.',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'checkoutToken'
  },
  'cartToken': {
    'description': 'Token of the cart that was used to create the order. NULL when no cart is associated.',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'cartToken'
  },
  'processedAt': {
    'description': 'The date and time when the order was processed.',
    'type': DATA_TYPES.TIMESTAMP,
    'graphqlPath': 'processedAt'
  },
  'closedAt': {
    'description': 'The date and time when the order was closed.',
    'type': DATA_TYPES.TIMESTAMP,
    'graphqlPath': 'closedAt'
  },
  'createdAt': {
    'description': 'The date and time when the order was created.',
    'type': DATA_TYPES.TIMESTAMP,
    'graphqlPath': 'createdAt'
  },
  'updatedAt': {
    'description': 'The date and time when the order was last updated.',
    'type': DATA_TYPES.TIMESTAMP,
    'graphqlPath': 'updatedAt'
  },
  'customer': {
    'description': 'Full customer object as JSON (id, email, phone, defaultAddress).',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'customer { id email phone defaultAddress { country city province } }'
  },
  'currentTotalDiscounts': {
    'description': 'The current total discounts (after edits).',
    'type': DATA_TYPES.NUMBER,
    'graphqlPath': 'currentTotalDiscountsSet { shopMoney { amount } }'
  },
  'currentTotalTax': {
    'description': 'The current total tax (after edits).',
    'type': DATA_TYPES.NUMBER,
    'graphqlPath': 'currentTotalTaxSet { shopMoney { amount } }'
  },
  'lineItems': {
    'description': 'The line items in the order as JSON array.',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'lineItems(first: 250) { nodes { id name title sku vendor quantity originalUnitPriceSet { shopMoney { amount } } discountedUnitPriceSet { shopMoney { amount } } } }'
  },
  'shippingLines': {
    'description': 'Shipping lines as JSON array.',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'shippingLines(first: 50) { nodes { id title discountedPriceSet { shopMoney { amount } } originalPriceSet { shopMoney { amount } } } }'
  },
  'refunds': {
    'description': 'Refunds as JSON array.',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'refunds(first: 50) { id createdAt note totalRefundedSet { shopMoney { amount } } refundLineItems(first: 50) { nodes { lineItem { id } quantity subtotalSet { shopMoney { amount } } } } }'
  }
};
