/**
 * Copyright (c) OWOX, Inc.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

// API reference: https://shopify.dev/docs/api/admin-graphql/2026-07/objects/Order

var ordersFields = {
  'id': {
    'description': 'A globally-unique ID.',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'id'
  },
  'name': {
    'description': 'The order name, generated by combining the order_number with the shop order prefix.',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'name'
  },
  'email': {
    'description': 'The email address of the customer.',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'email'
  },
  'phone': {
    'description': 'The phone number of the customer.',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'phone'
  },
  'displayFinancialStatus': {
    'description': 'The financial status of the order.',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'displayFinancialStatus'
  },
  'displayFulfillmentStatus': {
    'description': 'The fulfillment status of the order.',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'displayFulfillmentStatus'
  },
  'confirmed': {
    'description': 'Whether the order is confirmed.',
    'type': DATA_TYPES.BOOLEAN,
    'graphqlPath': 'confirmed'
  },
  'closed': {
    'description': 'Whether the order is closed.',
    'type': DATA_TYPES.BOOLEAN,
    'graphqlPath': 'closed'
  },
  'cancelledAt': {
    'description': 'The date and time when the order was cancelled.',
    'type': DATA_TYPES.TIMESTAMP,
    'graphqlPath': 'cancelledAt'
  },
  'cancelReason': {
    'description': 'The reason for cancellation.',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'cancelReason'
  },
  'currencyCode': {
    'description': 'The currency of the order.',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'currencyCode'
  },
  'subtotalPrice': {
    'description': 'The subtotal price of the order.',
    'type': DATA_TYPES.NUMBER,
    'graphqlPath': 'subtotalPriceSet { shopMoney { amount } }'
  },
  'totalPrice': {
    'description': 'The total price of the order.',
    'type': DATA_TYPES.NUMBER,
    'graphqlPath': 'totalPriceSet { shopMoney { amount } }'
  },
  'totalTax': {
    'description': 'The total tax of the order.',
    'type': DATA_TYPES.NUMBER,
    'graphqlPath': 'totalTaxSet { shopMoney { amount } }'
  },
  'totalShippingPrice': {
    'description': 'The total shipping price.',
    'type': DATA_TYPES.NUMBER,
    'graphqlPath': 'totalShippingPriceSet { shopMoney { amount } }'
  },
  'totalDiscounts': {
    'description': 'The total discounts applied.',
    'type': DATA_TYPES.NUMBER,
    'graphqlPath': 'totalDiscountsSet { shopMoney { amount } }'
  },
  'discountCodes': {
    'description': 'Discount codes applied to the order as JSON array (code, amount, type).',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'discountCodes'
  },
  'discountApplications': {
    'description': 'All discount applications (codes, automatic, manual, script) as JSON array, ordered by index. Shipping discounts allocate to shipping lines, not to lineItems discountAllocations.',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'discountApplications(first: 20) { nodes { index __typename allocationMethod targetSelection targetType value { ... on MoneyV2 { amount currencyCode } ... on PricingPercentageValue { percentage } } ... on DiscountCodeApplication { code } ... on AutomaticDiscountApplication { title } ... on ManualDiscountApplication { title description } ... on ScriptDiscountApplication { title } } }'
  },
  'totalRefunded': {
    'description': 'The total amount refunded.',
    'type': DATA_TYPES.NUMBER,
    'graphqlPath': 'totalRefundedSet { shopMoney { amount } }'
  },
  'totalOutstanding': {
    'description': 'The total amount not yet transacted for the order.',
    'type': DATA_TYPES.NUMBER,
    'graphqlPath': 'totalOutstandingSet { shopMoney { amount } }'
  },
  'totalWeight': {
    'description': 'The total weight of the order.',
    'type': DATA_TYPES.NUMBER,
    'graphqlPath': 'totalWeight'
  },
  'fullyPaid': {
    'description': 'Whether the order is fully paid.',
    'type': DATA_TYPES.BOOLEAN,
    'graphqlPath': 'fullyPaid'
  },
  'taxesIncluded': {
    'description': 'Whether taxes are included in the order subtotal.',
    'type': DATA_TYPES.BOOLEAN,
    'graphqlPath': 'taxesIncluded'
  },
  'taxExempt': {
    'description': 'Whether the order is tax exempt.',
    'type': DATA_TYPES.BOOLEAN,
    'graphqlPath': 'taxExempt'
  },
  'customerId': {
    'description': 'The ID of the customer.',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'customer { id }'
  },
  'customerEmail': {
    'description': 'The email of the customer.',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'customer { email }'
  },
  'shippingAddressCity': {
    'description': 'City from the shipping address.',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'shippingAddress { city }'
  },
  'shippingAddressCountry': {
    'description': 'Country from the shipping address.',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'shippingAddress { country }'
  },
  'shippingAddressProvince': {
    'description': 'Province from the shipping address.',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'shippingAddress { province }'
  },
  'shippingAddressZip': {
    'description': 'Postal/ZIP code from the shipping address.',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'shippingAddress { zip }'
  },
  'billingAddressCity': {
    'description': 'City from the billing address.',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'billingAddress { city }'
  },
  'billingAddressCountry': {
    'description': 'Country from the billing address.',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'billingAddress { country }'
  },
  'billingAddressProvince': {
    'description': 'Province from the billing address.',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'billingAddress { province }'
  },
  'billingAddressZip': {
    'description': 'Postal/ZIP code from the billing address.',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'billingAddress { zip }'
  },
  'tags': {
    'description': 'A comma-separated list of tags.',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'tags'
  },
  'note': {
    'description': 'The note attached to the order.',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'note'
  },
  'sourceName': {
    'description': 'The source of the order.',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'sourceName'
  },
  'checkoutToken': {
    'description': 'Token of the checkout that created the order. Useful for correlating the order with Web Pixel checkout events. NULL when no checkout is associated.',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'checkoutToken'
  },
  'cartToken': {
    'description': 'Token of the cart that was used to create the order. NULL when no cart is associated.',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'cartToken'
  },
  'processedAt': {
    'description': 'The date and time when the order was processed.',
    'type': DATA_TYPES.TIMESTAMP,
    'graphqlPath': 'processedAt'
  },
  'closedAt': {
    'description': 'The date and time when the order was closed.',
    'type': DATA_TYPES.TIMESTAMP,
    'graphqlPath': 'closedAt'
  },
  'createdAt': {
    'description': 'The date and time when the order was created.',
    'type': DATA_TYPES.TIMESTAMP,
    'graphqlPath': 'createdAt'
  },
  'updatedAt': {
    'description': 'The date and time when the order was last updated.',
    'type': DATA_TYPES.TIMESTAMP,
    'graphqlPath': 'updatedAt'
  },
  'customer': {
    'description': 'Full customer object as JSON (id, email, phone, defaultAddress).',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'customer { id email phone defaultAddress { country city province } }'
  },
  'currentTotalDiscounts': {
    'description': 'The current total discounts (after edits).',
    'type': DATA_TYPES.NUMBER,
    'graphqlPath': 'currentTotalDiscountsSet { shopMoney { amount } }'
  },
  'currentTotalTax': {
    'description': 'The current total tax (after edits).',
    'type': DATA_TYPES.NUMBER,
    'graphqlPath': 'currentTotalTaxSet { shopMoney { amount } }'
  },
  'number': {
    'description': "The order number used to generate the order name (with the shop's order number prefix/suffix). Not guaranteed to be unique.",
    'type': DATA_TYPES.INTEGER,
    'graphqlPath': 'number'
  },
  'confirmationNumber': {
    'description': 'A customer-facing order identifier, shown in some surfaces instead of the sequential order name. Not guaranteed to be unique.',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'confirmationNumber'
  },
  'legacyResourceId': {
    'description': 'The ID of the corresponding resource in the REST Admin API.',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'legacyResourceId'
  },
  'test': {
    'description': 'Whether the order was placed in test mode.',
    'type': DATA_TYPES.BOOLEAN,
    'graphqlPath': 'test'
  },
  'edited': {
    'description': 'Whether the order has had any edits applied after creation.',
    'type': DATA_TYPES.BOOLEAN,
    'graphqlPath': 'edited'
  },
  'originalTotalPrice': {
    'description': 'The total price of the order at the time it was created.',
    'type': DATA_TYPES.NUMBER,
    'graphqlPath': 'originalTotalPriceSet { shopMoney { amount } }'
  },
  'currentTotalPrice': {
    'description': 'The total price of the order, after returns.',
    'type': DATA_TYPES.NUMBER,
    'graphqlPath': 'currentTotalPriceSet { shopMoney { amount } }'
  },
  'netPayment': {
    'description': 'The net payment for the order (total received minus total refunded).',
    'type': DATA_TYPES.NUMBER,
    'graphqlPath': 'netPaymentSet { shopMoney { amount } }'
  },
  'totalReceived': {
    'description': 'The total amount received from the customer before returns.',
    'type': DATA_TYPES.NUMBER,
    'graphqlPath': 'totalReceivedSet { shopMoney { amount } }'
  },
  'totalCapturable': {
    'description': "The authorized amount that hasn't been captured yet.",
    'type': DATA_TYPES.NUMBER,
    'graphqlPath': 'totalCapturableSet { shopMoney { amount } }'
  },
  'totalTipReceived': {
    'description': 'The sum of all tip amounts for the order.',
    'type': DATA_TYPES.NUMBER,
    'graphqlPath': 'totalTipReceivedSet { shopMoney { amount } }'
  },
  'currentSubtotalPrice': {
    'description': 'The subtotal price of the order, after returns and refunds.',
    'type': DATA_TYPES.NUMBER,
    'graphqlPath': 'currentSubtotalPriceSet { shopMoney { amount } }'
  },
  'cartDiscountAmount': {
    'description': 'The total order-level (cart) discount amount applied at the time the order was created. Does not include line-level discounts.',
    'type': DATA_TYPES.NUMBER,
    'graphqlPath': 'cartDiscountAmountSet { shopMoney { amount } }'
  },
  'currentCartDiscountAmount': {
    'description': 'The current order-level (cart) discount amount after returns, refunds, order edits and cancellations. Does not include line-level discounts.',
    'type': DATA_TYPES.NUMBER,
    'graphqlPath': 'currentCartDiscountAmountSet { shopMoney { amount } }'
  },
  'currentShippingPrice': {
    'description': 'The current shipping price, after refunds and discounts.',
    'type': DATA_TYPES.NUMBER,
    'graphqlPath': 'currentShippingPriceSet { shopMoney { amount } }'
  },
  'totalRefundedShipping': {
    'description': 'The total amount of shipping that was refunded.',
    'type': DATA_TYPES.NUMBER,
    'graphqlPath': 'totalRefundedShippingSet { shopMoney { amount } }'
  },
  'currentTotalDuties': {
    'description': 'The current total import duties for the order, after returns or modifications.',
    'type': DATA_TYPES.NUMBER,
    'graphqlPath': 'currentTotalDutiesSet { shopMoney { amount } }'
  },
  'originalTotalDuties': {
    'description': 'The total import duties calculated when the order was created.',
    'type': DATA_TYPES.NUMBER,
    'graphqlPath': 'originalTotalDutiesSet { shopMoney { amount } }'
  },
  'currentTotalAdditionalFees': {
    'description': 'The current total of all additional fees for the order.',
    'type': DATA_TYPES.NUMBER,
    'graphqlPath': 'currentTotalAdditionalFeesSet { shopMoney { amount } }'
  },
  'originalTotalAdditionalFees': {
    'description': 'The total of all additional fees calculated when the order was created.',
    'type': DATA_TYPES.NUMBER,
    'graphqlPath': 'originalTotalAdditionalFeesSet { shopMoney { amount } }'
  },
  'refundDiscrepancy': {
    'description': 'The difference between the suggested and the actual refunded amount. Positive values favor the merchant, negative values favor the customer.',
    'type': DATA_TYPES.NUMBER,
    'graphqlPath': 'refundDiscrepancySet { shopMoney { amount } }'
  },
  'presentmentCurrencyCode': {
    'description': 'The currency the customer used when placing the order. Amount fields in this table are in the shop currency (currencyCode).',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'presentmentCurrencyCode'
  },
  'unpaid': {
    'description': 'Whether no payments have been made for the order.',
    'type': DATA_TYPES.BOOLEAN,
    'graphqlPath': 'unpaid'
  },
  'refundable': {
    'description': 'Whether the order can be refunded based on its payment transactions.',
    'type': DATA_TYPES.BOOLEAN,
    'graphqlPath': 'refundable'
  },
  'capturable': {
    'description': 'Whether an authorized payment on the order can be captured.',
    'type': DATA_TYPES.BOOLEAN,
    'graphqlPath': 'capturable'
  },
  'canMarkAsPaid': {
    'description': 'Whether the order can be manually marked as paid.',
    'type': DATA_TYPES.BOOLEAN,
    'graphqlPath': 'canMarkAsPaid'
  },
  'paymentGatewayNames': {
    'description': 'The names of all payment gateways used for the order, comma-separated.',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'paymentGatewayNames'
  },
  'estimatedTaxes': {
    'description': 'Whether taxes on the order are estimated.',
    'type': DATA_TYPES.BOOLEAN,
    'graphqlPath': 'estimatedTaxes'
  },
  'fulfillable': {
    'description': 'Whether the order has any line items that can be fulfilled.',
    'type': DATA_TYPES.BOOLEAN,
    'graphqlPath': 'fulfillable'
  },
  'requiresShipping': {
    'description': 'Whether the order requires physical shipping.',
    'type': DATA_TYPES.BOOLEAN,
    'graphqlPath': 'requiresShipping'
  },
  'subtotalLineItemsQuantity': {
    'description': 'The sum of quantities for all line items contributing to the subtotal.',
    'type': DATA_TYPES.INTEGER,
    'graphqlPath': 'subtotalLineItemsQuantity'
  },
  'currentSubtotalLineItemsQuantity': {
    'description': 'The current sum of quantities for all line items contributing to the subtotal, after returns.',
    'type': DATA_TYPES.INTEGER,
    'graphqlPath': 'currentSubtotalLineItemsQuantity'
  },
  'currentTotalWeight': {
    'description': 'The total weight of the order in grams, after returns and refunds.',
    'type': DATA_TYPES.NUMBER,
    'graphqlPath': 'currentTotalWeight'
  },
  'restockable': {
    'description': 'Whether any line items on the order can be restocked into inventory.',
    'type': DATA_TYPES.BOOLEAN,
    'graphqlPath': 'restockable'
  },
  'canNotifyCustomer': {
    'description': 'Whether order notifications can be sent to the customer.',
    'type': DATA_TYPES.BOOLEAN,
    'graphqlPath': 'canNotifyCustomer'
  },
  'statusPageUrl': {
    'description': "The URL where the customer can check the order's current status.",
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'statusPageUrl'
  },
  'hasTimelineComment': {
    'description': 'Whether the merchant added a timeline comment to the order.',
    'type': DATA_TYPES.BOOLEAN,
    'graphqlPath': 'hasTimelineComment'
  },
  'merchantEditable': {
    'description': 'Whether the order can be edited by the merchant.',
    'type': DATA_TYPES.BOOLEAN,
    'graphqlPath': 'merchantEditable'
  },
  'merchantEditableErrors': {
    'description': "Reasons why the order can't be edited, comma-separated. Empty when the order is editable.",
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'merchantEditableErrors'
  },
  'dutiesIncluded': {
    'description': 'Whether duties are included in the subtotal price of the order.',
    'type': DATA_TYPES.BOOLEAN,
    'graphqlPath': 'dutiesIncluded'
  },
  'poNumber': {
    'description': 'The purchase order number associated with the order.',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'poNumber'
  },
  'sourceIdentifier': {
    'description': 'A unique POS or third-party order identifier.',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'sourceIdentifier'
  },
  'registeredSourceUrl': {
    'description': 'The URL of the source the order originated from.',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'registeredSourceUrl'
  },
  'productNetwork': {
    'description': 'Whether the customer purchased items from other stores in the same network.',
    'type': DATA_TYPES.BOOLEAN,
    'graphqlPath': 'productNetwork'
  },
  'customerAcceptsMarketing': {
    'description': 'Whether the customer agreed to receive marketing emails at the time of purchase.',
    'type': DATA_TYPES.BOOLEAN,
    'graphqlPath': 'customerAcceptsMarketing'
  },
  'customerLocale': {
    'description': "The customer's language and region preference at the time of purchase.",
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'customerLocale'
  },
  'billingAddressMatchesShippingAddress': {
    'description': 'Whether the billing address matches the shipping address. False when either address is missing.',
    'type': DATA_TYPES.BOOLEAN,
    'graphqlPath': 'billingAddressMatchesShippingAddress'
  },
  'lineItems': {
    'description': 'The line items in the order as JSON array, with discount amounts and per-discount allocations (discountAllocations; join to discountApplications by index). See the connector guide for how the amounts differ.',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'lineItems(first: 250) { nodes { id name title sku vendor quantity currentQuantity originalUnitPriceSet { shopMoney { amount } } discountedUnitPriceSet { shopMoney { amount } } discountedUnitPriceAfterAllDiscountsSet { shopMoney { amount } } totalDiscountSet { shopMoney { amount } } discountAllocations { allocatedAmountSet { shopMoney { amount } } discountApplication { index __typename targetSelection ... on DiscountCodeApplication { code } ... on AutomaticDiscountApplication { title } ... on ManualDiscountApplication { title } ... on ScriptDiscountApplication { title } } } } }'
  },
  'shippingLines': {
    'description': 'Shipping lines as JSON array.',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'shippingLines(first: 50) { nodes { id title discountedPriceSet { shopMoney { amount } } originalPriceSet { shopMoney { amount } } } }'
  },
  'refunds': {
    'description': 'Refunds as JSON array.',
    'type': DATA_TYPES.STRING,
    'graphqlPath': 'refunds(first: 50) { id createdAt note totalRefundedSet { shopMoney { amount } } refundLineItems(first: 50) { nodes { lineItem { id } quantity subtotalSet { shopMoney { amount } } } } }'
  }
};
